# Generated by Django 3.1.7 on 2021-02-28 02:27

from django.db import migrations, models
import story.models


class Migration(migrations.Migration):

    dependencies = [
        ('story', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='problem',
            name='id',
        ),
        migrations.AddField(
            model_name='problem',
            name='image',
            field=models.ImageField(default='problem/999/default.png', upload_to=story.models.image_directory_path),
        ),
        migrations.AddField(
            model_name='problem',
            name='problem_ID',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
