# Generated by Django 3.1.7 on 2021-02-28 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('story', '0002_auto_20210228_0227'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='description',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
