# Generated by Django 3.1.7 on 2021-02-28 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('story', '0003_problem_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='problem',
            old_name='interested',
            new_name='idk_count',
        ),
    ]
